### ISSUE TITLE
Create TGP page

### ISSUE THREAD

**Issue by nf-s** [osgeo-oceania/foss4g-sotm-oceania-2024#11]
Pull content from newsletter - https://064rp.mjt.lu/nl3/aea6S7boBMT9ai5A1_seMA

**Comment by EmHain8** [comment]
Using the current doc, which is last years - amend with the following:

- Link to form: https://docs.google.com/forms/d/1NNPSqYvYDGnbr7u6Fz8bDGfQ8m5m49gbCzBPAs9kORI/viewform?edit_requested=true


Replace points with:     
- People from remote areas of the Oceania region, who wouldn't be able to attend without funding assistance.
- People attending the FOSS4G SoTM Conference for the first time.
- People from underrepresented communities, such as Indigenous communities; Residents of remote communities; and Women and minority genders.
- Community development workers or students who don’t have workplace or government funding 
- People who will make use of what they learn to make a positive impact on themselves and their communities.
- People who contribute to open communities, such as contributing to OpenStreetMap, or open source software.

Tiers
- NZD to AUD
• Tier 1: free conference & workshop registration, plus up to AUD $3000
• Tier 2: free conference & workshop registration, plus up to AUD $1000
• Tier 3: free conference & workshop registration only

Closing date: 1 June
Date recipient informed: 5th August

**Comment by nf-s** [comment]
Done https://2024.foss4g-oceania.org/#/attend/travel-grant-program
