### ISSUE TITLE
Create Accommodation page

### ISSUE THREAD

**Issue by EmHain8** [osgeo-oceania/foss4g-sotm-oceania-2024#12]
Add in accommodation options for the conference. More details to come

**Comment by EmHain8** [comment]
https://www.alabamahobart.com.au/

**Comment by EmHain8** [comment]
[Google Doc](https://docs.google.com/document/d/1EgGTaapD5gQbMGAWl3oYMRUnvxb9h492ZjKUa6pumBY/edit) with options

**Comment by nf-s** [comment]
Done - https://2024.foss4g-oceania.org/#/attend/accommodation

I removed Harrington's 102 as their website isn't working
