### ISSUE TITLE
Add to Adventures page

### ISSUE THREAD

**Issue by EmHain8** [osgeo-oceania/foss4g-sotm-oceania-2024#27]
[Hobart - Must See Attractions & Things To Do (tasmania.com)](https://tasmania.com/points-of-interest/hobart/)

**Comment by nf-s** [comment]
Done!

- https://github.com/osgeo-oceania/foss4g-sotm-oceania-2024/commit/96ff4f124d8bee4123f70005e81de229816b82a1
