### ISSUE TITLE
Don't zoom map on mouse scroll

### ISSUE THREAD

**Issue by alexgleith** [osgeo-oceania/foss4g-sotm-oceania-2024#5]
Just a bit of UX. Maybe include the google thing where they need you to hold control to zoom or something.

**Comment by nf-s** [comment]
Closed by https://github.com/osgeo-oceania/foss4g-sotm-oceania-2024/commit/7d22d6f7077d5d379c6d496e461087862586f093

<img width="495" alt="Screenshot 2024-03-30 at 12 39 34" src="https://github.com/osgeo-oceania/foss4g-sotm-oceania-2024/assets/6187649/190d2136-c2ab-48ef-9a0c-50fb2398901d">
