### ISSUE TITLE
Pretalx and MD descriptions

### ISSUE THREAD

**Issue by EmHain8** [osgeo-oceania/foss4g-sotm-oceania-2024#54]
If md is used in the description for a pretalx entry, it appears on the website in the md format. In pretalx, it appears formatted as directed by the md. 
![image](https://github.com/user-attachments/assets/c8e3e531-e3c5-423c-914c-e295475de58b)

**Comment by nf-s** [comment]
Fixed!

I went into pretalx and made sure it was valid markdown
