### ISSUE TITLE
Add signup to the mailing list form iframe somewhere

### ISSUE THREAD

**Issue by alexgleith** [osgeo-oceania/foss4g-sotm-oceania-2024#7]
Iframe:

```
<iframe data-w-type="embedded" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://064rp.mjt.lu/wgt/064rp/xlvi/form?c=7f052458" width="100%" style="height: 0;"></iframe>

<script type="text/javascript" src="https://app.mailjet.com/pas-nc-embedded-v1.js"></script>
```

Not sure where it shouold go! The form is tested and works though.

**Comment by nf-s** [comment]
Closed by https://github.com/osgeo-oceania/foss4g-sotm-oceania-2024/commit/49a1c045961e8dc3359bc28a182824127de9252f

- https://2024.foss4g-oceania.org/#/mailing-list

I added the following links

## On the home page and footer

<img width="1206" alt="image" src="https://github.com/osgeo-oceania/foss4g-sotm-oceania-2024/assets/6187649/633a4611-3b35-4700-947d-d6ec347106ea">


## On the placeholder register page

<img width="1075" alt="image" src="https://github.com/osgeo-oceania/foss4g-sotm-oceania-2024/assets/6187649/01f87886-a16e-4147-9ab2-070b35babdf5">

**Comment by alexgleith** [comment]
Neat 🚀
