### ISSUE TITLE
Add Code of Conduct page

### ISSUE THREAD

**Issue by alexgleith** [osgeo-oceania/foss4g-sotm-oceania-2024#9]

**Comment by nf-s** [comment]
We have a code of conduct page here

- https://2024.foss4g-oceania.org/#/code-of-conduct

It is linked in the footer

**Comment by nf-s** [comment]
I can add it to the header nav bar

**Comment by alexgleith** [comment]
Oh, awesome!

Yeah, maybe to the "attend" ... or should we have a "resources" gorup perhaps?

**Comment by johnwbryant** [comment]
I just noticed the text of the CoC looks like it was taken from here: 

https://www.osgeo.org/resources/osgeo-code-of-conduct/

That page says "This static document is no longer maintained. OSGeo recommends use of live documents as outlined on our [code-of-conduct](https://www.osgeo.org/code_of_conduct/) page."

I don't know if there are any specific issues with it, but thought it worth pointing out.

**Comment by alexgleith** [comment]
Good point.

Maybe @nf-s we direct people to the OSGeo CoC without reproducing it, and we can simply include contact details, including the Chair of the conference as well as perhaps an email for the Chair of the OSGeo Oceania email.

**Comment by nf-s** [comment]
I have updated the page to point to the Berlin CoC

> # Code of Conduct
> 
> FOSS4G SotM Oceania 2024 has adopted the [Berlin Code of Conduct](https://berlincodeofconduct.org/), all who attend our events or participate on our mailing list are expected to have read this document, and to behave accordingly.
>
> ## Reporting Guidelines
> 
> If you believe someone is breaking this code of conduct, you may reply to them, and point to this code of conduct. Such messages may be in public or in private, whatever is most appropriate. Assume good faith; it is more likely that participants are unaware of their bad behaviour than that they intentionally try to degrade the quality of the discussion. Should there be difficulties in dealing with the situation, you may report your concerns to event staff, a conference committee member or the OSGeo Oceania Board. Serious or persistent offenders may be expelled from the event or forum by event organizers or forum leaders.
> 
> ## Contact Information
> 
> You can email the FOSS4G Oceania organizing team with any concerns at [chair@foss4g-oceania.org](mailto:chair@foss4g-oceania.org).

**Comment by alexgleith** [comment]
I extremely love it, @nf-s! Nice work :-)
